version: "3.9"

services:
  api:
    container_name: api-beecar
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB_USER=ADMIN
      - DB=beecar
      - SECRET_KEY=ataldachave
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db-beecar
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=ADMIN
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=beecar
